# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ulaş Akdeniz
tagline:             'Personal blog'
description:         'Ulaş Akdeniz - Personal Blog'
url:                 http://ulasakdeniz.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Ulaş Akdeniz
  url:               http://ulasakdeniz.com
  email:             akdenizulas@gmail.com

# Custom vars
version:             1.0.0
