# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:               Ulaş Akdeniz
tagline:             'Personal Blog'
description:         'Ulaş Akdeniz'
url:                 https://ulasakdeniz.com
baseurl:         
paginate:            5

# About/contact
author:
  name:              Ulaş Akdeniz
  url:               https://ulasakdeniz.com
  email:             akdenizulas@gmail.com

# Custom vars
version:             1.0.0
